#Example configuration options that can be placed in your main SiriProxy config.yml

##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################
    
    - name: 'Sports'
      git: 'git://github.com/dtomcat/SiriProxy-Sports.git'
      nba_url: 'http://www.yourserver.com/nbafile.php'
      nfl_url: 'http://www.yourserver.com/nflfile.php'